"""post journey episode uniqueness

Revision ID: 1c683806cbae
Revises: 3069f0e7df6a
Create Date: 2026-05-07 18:01:37.637200

"""
from typing import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '1c683806cbae'
down_revision: str | Sequence[str] | None = '3069f0e7df6a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_journey_episode'), table_name='posts')
    op.create_unique_constraint('uq_posts_journey_episode', 'posts', ['journey_id', 'episode_no'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_posts_journey_episode', 'posts', type_='unique')
    op.create_index(op.f('ix_posts_journey_episode'), 'posts', ['journey_id', 'episode_no'], unique=False)
    # ### end Alembic commands ###
