"""add primary_region_id to users

Revision ID: 3069f0e7df6a
Revises: ced387721bee
Create Date: 2026-05-06 17:42:01.312190

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3069f0e7df6a'
down_revision: str | Sequence[str] | None = 'ced387721bee'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('primary_region_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_primary_region_id'), 'users', ['primary_region_id'], unique=False)
    op.create_foreign_key(None, 'users', 'regions', ['primary_region_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_primary_region_id'), table_name='users')
    op.drop_column('users', 'primary_region_id')
    # ### end Alembic commands ###
