"""add posts and link images.post_id fk

Revision ID: 30a9afade274
Revises: aa84fdc8e446
Create Date: 2026-05-06 14:47:12.799190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30a9afade274'
down_revision: Union[str, Sequence[str], None] = 'aa84fdc8e446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('journey_id', sa.Integer(), nullable=True),
    sa.Column('parent_post_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('review', 'journey_episode', 'question', 'answer', 'plan', name='post_type'), nullable=False),
    sa.Column('episode_no', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'hidden', name='post_status'), server_default='draft', nullable=False),
    sa.Column('view_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_post_id'], ['posts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_posts_author_published', 'posts', ['author_id', 'published_at'], unique=False)
    op.create_index('ix_posts_journey_episode', 'posts', ['journey_id', 'episode_no'], unique=False)
    op.create_index('ix_posts_metadata_gin', 'posts', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index('ix_posts_region_published', 'posts', ['region_id', 'published_at'], unique=False)
    op.create_index('ix_posts_type_status_published', 'posts', ['type', 'status', 'published_at'], unique=False)
    op.create_foreign_key('fk_images_post_id_posts', 'images', 'posts', ['post_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_images_post_id_posts', 'images', type_='foreignkey')
    op.drop_index('ix_posts_type_status_published', table_name='posts')
    op.drop_index('ix_posts_region_published', table_name='posts')
    op.drop_index('ix_posts_metadata_gin', table_name='posts', postgresql_using='gin')
    op.drop_index('ix_posts_journey_episode', table_name='posts')
    op.drop_index('ix_posts_author_published', table_name='posts')
    op.drop_table('posts')
    op.execute("DROP TYPE post_status")
    op.execute("DROP TYPE post_type")
    # ### end Alembic commands ###
