"""user v1.1 columns

Revision ID: 64f2f6e5cd8d
Revises: fdd7025f8743
Create Date: 2026-05-06 14:19:05.039491

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64f2f6e5cd8d'
down_revision: str | Sequence[str] | None = 'fdd7025f8743'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE badge_level ADD VALUE IF NOT EXISTS 'ex_resident'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('resident_revalidated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('ex_resident_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('anonymized_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'anonymized_at')
    op.drop_column('users', 'ex_resident_at')
    op.drop_column('users', 'resident_revalidated_at')
    # ### end Alembic commands ###
