"""add notifications

Revision ID: 8f34f508871a
Revises: ba7847bd86c2
Create Date: 2026-05-06 15:39:01.097794

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f34f508871a'
down_revision: str | Sequence[str] | None = 'ba7847bd86c2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('badge_approved', 'badge_rejected', 'post_comment', 'post_liked', 'journey_new_episode', 'question_answered', 'revalidation_prompt', 'timelapse_remind', 'system', name='notification_type'), nullable=False),
    sa.Column('source_user_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_unread_created', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_user_unread_created', table_name='notifications')
    op.drop_table('notifications')
    op.execute('DROP TYPE notification_type')
    # ### end Alembic commands ###
