"""add post_validations

Revision ID: b58282825ad8
Revises: 30a9afade274
Create Date: 2026-05-06 14:56:04.147935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b58282825ad8'
down_revision: Union[str, Sequence[str], None] = '30a9afade274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('validator_user_id', sa.Integer(), nullable=False),
    sa.Column('vote', sa.Enum('confirm', 'dispute', name='validation_vote'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validator_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'validator_user_id', name='uq_post_validations_post_validator')
    )
    op.create_index('ix_post_validations_post_vote', 'post_validations', ['post_id', 'vote'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_validations_post_vote', table_name='post_validations')
    op.drop_table('post_validations')
    op.execute("DROP TYPE validation_vote")
    # ### end Alembic commands ###
