"""add badge applications and evidence

Revision ID: ba7847bd86c2
Revises: 18fd0e2d11d9
Create Date: 2026-05-06 15:18:10.568416

"""
from typing import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'ba7847bd86c2'
down_revision: str | Sequence[str] | None = '18fd0e2d11d9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE evidence_type")
    op.execute("DROP TYPE badge_application_status")
    op.execute("DROP TYPE badge_requested_level")
    # ### end Alembic commands ###
