"""add profile edit columns to users

Revision ID: bc70466dfb57
Revises: f493042da765
Create Date: 2026-05-13 13:26:13.361046

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc70466dfb57'
down_revision: str | Sequence[str] | None = 'f493042da765'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_image_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('username_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('notify_email_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('notify_kakao_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_users_avatar_image_id'), 'users', ['avatar_image_id'], unique=False)
    op.create_foreign_key(None, 'users', 'images', ['avatar_image_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_avatar_image_id'), table_name='users')
    op.drop_column('users', 'notify_kakao_enabled')
    op.drop_column('users', 'notify_email_enabled')
    op.drop_column('users', 'username_changed_at')
    op.drop_column('users', 'avatar_image_id')
    # ### end Alembic commands ###
