"""add images

Revision ID: d72712a22091
Revises: 33ad329ff829
Create Date: 2026-05-06 14:28:58.597826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd72712a22091'
down_revision: Union[str, Sequence[str], None] = '33ad329ff829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('file_path_orig', sa.String(length=512), nullable=False),
    sa.Column('file_path_thumb', sa.String(length=512), nullable=True),
    sa.Column('file_path_medium', sa.String(length=512), nullable=True),
    sa.Column('file_path_webp', sa.String(length=512), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('order_idx', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('processing', 'ready', 'failed', name='image_status'), server_default='processing', nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_owner_id'), 'images', ['owner_id'], unique=False)
    op.create_index(op.f('ix_images_post_id'), 'images', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_post_id'), table_name='images')
    op.drop_index(op.f('ix_images_owner_id'), table_name='images')
    op.drop_table('images')
    op.execute("DROP TYPE image_status")
    # ### end Alembic commands ###
